/*
** ###################################################################
**
**     Copyright (c) 2016 Freescale Semiconductor, Inc.
**     Copyright 2017-2019 NXP
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of the copyright holder nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**
** ###################################################################
*/

/*==========================================================================*/
/*!
 * @file
 *
 * Header file containing local resource defines for the ADMA subsystem.
 *
 * @addtogroup ADMA_SS
 * @{
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by bin/rsrc_ss_h.pl */

#ifndef SC_SS_ADMA_RSRC_H
#define SC_SS_ADMA_RSRC_H

/*!
 * @name Defines for local SS resource indexes
 */
/*@{*/
#define SS_R_ASRC_0              0U
#define SS_R_ESAI_0              1U
#define SS_R_SPDIF_0             2U
#define SS_R_SAI_0               3U
#define SS_R_SAI_1               4U
#define SS_R_SAI_2               5U
#define SS_R_SAI_3               6U
#define SS_R_GPT_5               7U
#define SS_R_GPT_6               8U
#define SS_R_GPT_7               9U
#define SS_R_GPT_8               10U
#define SS_R_GPT_9               11U
#define SS_R_GPT_10              12U
#define SS_R_DMA_0_CH0           13U
#define SS_R_DMA_0_CH1           14U
#define SS_R_DMA_0_CH2           15U
#define SS_R_DMA_0_CH3           16U
#define SS_R_DMA_0_CH4           17U
#define SS_R_DMA_0_CH5           18U
#define SS_R_DMA_0_CH6           19U
#define SS_R_DMA_0_CH7           20U
#define SS_R_DMA_0_CH8           21U
#define SS_R_DMA_0_CH9           22U
#define SS_R_DMA_0_CH10          23U
#define SS_R_DMA_0_CH11          24U
#define SS_R_DMA_0_CH12          25U
#define SS_R_DMA_0_CH13          26U
#define SS_R_DMA_0_CH14          27U
#define SS_R_DMA_0_CH15          28U
#define SS_R_DMA_0_CH16          29U
#define SS_R_DMA_0_CH17          30U
#define SS_R_DMA_0_CH18          31U
#define SS_R_DMA_0_CH19          32U
#define SS_R_DMA_0_CH20          33U
#define SS_R_DMA_0_CH21          34U
#define SS_R_DMA_0_CH22          35U
#define SS_R_DMA_0_CH23          36U
#define SS_R_DMA_0_CH24          37U
#define SS_R_DMA_0_CH25          38U
#define SS_R_DMA_0_CH26          39U
#define SS_R_DMA_0_CH27          40U
#define SS_R_DMA_0_CH28          41U
#define SS_R_DMA_0_CH29          42U
#define SS_R_DMA_0_CH30          43U
#define SS_R_DMA_0_CH31          44U
#define SS_R_ASRC_1              45U
#define SS_R_SAI_4               46U
#define SS_R_SAI_5               47U
#define SS_R_AMIX                48U
#define SS_R_MQS_0               49U
#define SS_R_DMA_1_CH0           50U
#define SS_R_DMA_1_CH1           51U
#define SS_R_DMA_1_CH2           52U
#define SS_R_DMA_1_CH3           53U
#define SS_R_DMA_1_CH4           54U
#define SS_R_DMA_1_CH5           55U
#define SS_R_DMA_1_CH6           56U
#define SS_R_DMA_1_CH7           57U
#define SS_R_DMA_1_CH8           58U
#define SS_R_DMA_1_CH9           59U
#define SS_R_DMA_1_CH10          60U
#define SS_R_DMA_1_CH11          61U
#define SS_R_DMA_1_CH12          62U
#define SS_R_DMA_1_CH13          63U
#define SS_R_DMA_1_CH14          64U
#define SS_R_DMA_1_CH15          65U
#define SS_R_SPI_0               66U
#define SS_R_SPI_1               67U
#define SS_R_SPI_2               68U
#define SS_R_SPI_3               69U
#define SS_R_UART_0              70U
#define SS_R_UART_1              71U
#define SS_R_UART_2              72U
#define SS_R_UART_3              73U
#define SS_R_DMA_2_CH0           74U
#define SS_R_DMA_2_CH1           75U
#define SS_R_DMA_2_CH2           76U
#define SS_R_DMA_2_CH3           77U
#define SS_R_DMA_2_CH4           78U
#define SS_R_DMA_2_CH5           79U
#define SS_R_DMA_2_CH6           80U
#define SS_R_DMA_2_CH7           81U
#define SS_R_DMA_2_CH8           82U
#define SS_R_DMA_2_CH9           83U
#define SS_R_DMA_2_CH10          84U
#define SS_R_DMA_2_CH11          85U
#define SS_R_DMA_2_CH12          86U
#define SS_R_DMA_2_CH13          87U
#define SS_R_DMA_2_CH14          88U
#define SS_R_DMA_2_CH15          89U
#define SS_R_DMA_2_CH16          90U
#define SS_R_DMA_2_CH17          91U
#define SS_R_DMA_2_CH18          92U
#define SS_R_DMA_2_CH19          93U
#define SS_R_DMA_2_CH20          94U
#define SS_R_DMA_2_CH21          95U
#define SS_R_DMA_2_CH22          96U
#define SS_R_DMA_2_CH23          97U
#define SS_R_DMA_2_CH24          98U
#define SS_R_DMA_2_CH25          99U
#define SS_R_DMA_2_CH26          100U
#define SS_R_DMA_2_CH27          101U
#define SS_R_DMA_2_CH28          102U
#define SS_R_DMA_2_CH29          103U
#define SS_R_DMA_2_CH30          104U
#define SS_R_DMA_2_CH31          105U
#define SS_R_I2C_0               106U
#define SS_R_I2C_1               107U
#define SS_R_I2C_2               108U
#define SS_R_I2C_3               109U
#define SS_R_ADC_0               110U
#define SS_R_FTM_0               111U
#define SS_R_FTM_1               112U
#define SS_R_CAN_0               113U
#define SS_R_CAN_1               114U
#define SS_R_CAN_2               115U
#define SS_R_DMA_3_CH0           116U
#define SS_R_DMA_3_CH1           117U
#define SS_R_DMA_3_CH2           118U
#define SS_R_DMA_3_CH3           119U
#define SS_R_DMA_3_CH4           120U
#define SS_R_DMA_3_CH5           121U
#define SS_R_DMA_3_CH6           122U
#define SS_R_DMA_3_CH7           123U
#define SS_R_DMA_3_CH8           124U
#define SS_R_DMA_3_CH9           125U
#define SS_R_DMA_3_CH10          126U
#define SS_R_DMA_3_CH11          127U
#define SS_R_DMA_3_CH12          128U
#define SS_R_DMA_3_CH13          129U
#define SS_R_DMA_3_CH14          130U
#define SS_R_DMA_3_CH15          131U
#define SS_R_IRQSTR_M4_0         132U
#define SS_R_IRQSTR_M4_1         133U
#define SS_R_GIC                 134U
#define SS_R_DSP                 135U
#define SS_R_DSP_RAM             136U
#define SS_R_LCD_0               137U
#define SS_R_LCD_0_PWM_0         138U
#define SS_R_AUDIO_PLL_0         139U
#define SS_R_AUDIO_PLL_1         140U
#define SS_R_AUDIO_CLK_0         141U
#define SS_R_AUDIO_CLK_1         142U
#define SS_R_MCLK_OUT_0          143U
#define SS_R_MCLK_OUT_1          144U
#define SS_R_IRQSTR_SCU2         145U
#define SS_R_IRQSTR_DSP          146U
#define SS_R_ELCDIF_PLL          147U
/*@}*/

#endif /* SC_SS_ADMA_RSRC_H */

/**@}*/

