
OBJS += $(OUT)/svc/rm/svc.o

RPCS += $(OUT)/svc/rm/rpc_srv.o

RPCL += $(OUT)/svc/rm/rpc_clnt.o

RPCH += $(SRC)/svc/rm/rpc.h

RPCC += $(SRC)/svc/rm/rpc_srv.c		 \
		$(SRC)/svc/rm/rpc_clnt.c     \
		$(SRC)/svc/rm/rpc_xlate.c

DIRS += $(OUT)/svc/rm

