
OBJS += $(OUT)/board/none/board.o $(OUT)/board/board_common.o

ifneq ($(HW), SIMU)
    OBJS += $(OUT)/board/board.o
endif

DIRS += $(OUT)/board/none

RSRC_MD += $(SRC)/board/none/resource.txt

CTRL_MD += $(SRC)/board/none/control.txt

