
OBJS += $(OUT)/ss/vpu/v5/ss.o

CONFIGH += $(SRC)/ss/vpu/v5/config.h $(SRC)/ss/vpu/v5/rsrc.h

RSRC_MD += $(SRC)/ss/vpu/v5/resource.txt

CLK_MD += $(SRC)/ss/vpu/v5/clock.txt

CTRL_MD += $(SRC)/ss/vpu/v5/control.txt

DIRS += $(OUT)/ss/vpu/v5

