
OBJS += $(OUT)/drivers/analog/fsl_analog.o
OBJS += $(OUT)/drivers/analog/fsl_analog_refgen.o
OBJS += $(OUT)/drivers/analog/fsl_analog_fbb.o
OBJS += $(OUT)/drivers/analog/fsl_analog_pll.o

DIRS += $(OUT)/drivers/analog

