/*
** ###################################################################
**
**     Copyright (c) 2016 Freescale Semiconductor, Inc.
**     Copyright 2017-2021 NXP
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of the copyright holder nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**
** ###################################################################
*/

/*==========================================================================*/
/*!
 * @file
 *
 * Header file used to restrict pad mux settings based on resource ownership.
 */
/*==========================================================================*/

/* DO NOT EDIT - This file auto generated by bin/perl/pad_priority_h.pl */

#ifndef SC_PAD_PRIORITY_H
#define SC_PAD_PRIORITY_H

/* Defines */

#define SC_PAD_PRIORITY_INIT \
    PNFO(USB_SS3_TC0, 0, I2C_1), \
    PNFO(USB_SS3_TC0, 2, USB_2), \
    PNFO(USB_SS3_TC1, 0, I2C_1), \
    PNFO(USB_SS3_TC1, 1, USB_2), \
    PNFO(USB_SS3_TC2, 0, I2C_1), \
    PNFO(USB_SS3_TC2, 2, USB_2), \
    PNFO(USB_SS3_TC3, 0, I2C_1), \
    PNFO(USB_SS3_TC3, 1, USB_2), \
    PNFO(EMMC0_CMD, 1, NAND), \
    PNFO(EMMC0_DATA6, 2, MLB_0), \
    PNFO(EMMC0_DATA7, 2, MLB_0), \
    PNFO(EMMC0_STROBE, 2, MLB_0), \
    PNFO(USDHC1_RESET_B, 0, SDHC_1), \
    PNFO(USDHC1_RESET_B, 2, SPI_2), \
    PNFO(USDHC1_VSELECT, 0, SDHC_1), \
    PNFO(USDHC1_VSELECT, 2, SPI_2), \
    PNFO(USDHC1_VSELECT, 3, NAND), \
    PNFO(USDHC1_WP, 0, SDHC_1), \
    PNFO(USDHC1_WP, 2, SPI_2), \
    PNFO(USDHC1_CD_B, 0, SDHC_1), \
    PNFO(USDHC1_CD_B, 2, SPI_2), \
    PNFO(USDHC1_CD_B, 3, NAND), \
    PNFO(USDHC1_CLK, 0, SDHC_1), \
    PNFO(USDHC1_CLK, 1, UART_3), \
    PNFO(USDHC1_CMD, 0, SDHC_1), \
    PNFO(USDHC1_CMD, 1, NAND), \
    PNFO(USDHC1_CMD, 2, MQS_0), \
    PNFO(USDHC1_DATA0, 0, SDHC_1), \
    PNFO(USDHC1_DATA0, 1, NAND), \
    PNFO(USDHC1_DATA0, 2, MQS_0), \
    PNFO(USDHC1_DATA1, 0, SDHC_1), \
    PNFO(USDHC1_DATA1, 1, NAND), \
    PNFO(USDHC1_DATA1, 2, UART_3), \
    PNFO(USDHC1_DATA2, 0, SDHC_1), \
    PNFO(USDHC1_DATA2, 1, NAND), \
    PNFO(USDHC1_DATA3, 0, SDHC_1), \
    PNFO(USDHC1_DATA3, 1, NAND), \
    PNFO(ENET0_RGMII_TXC, 3, NAND), \
    PNFO(ENET0_RGMII_TX_CTL, 1, SDHC_1), \
    PNFO(ENET0_RGMII_TXD0, 1, SDHC_1), \
    PNFO(ENET0_RGMII_TXD1, 1, SDHC_1), \
    PNFO(ENET0_RGMII_TXD2, 1, MLB_0), \
    PNFO(ENET0_RGMII_TXD2, 2, NAND), \
    PNFO(ENET0_RGMII_TXD2, 3, SDHC_1), \
    PNFO(ENET0_RGMII_TXD3, 1, MLB_0), \
    PNFO(ENET0_RGMII_TXD3, 2, NAND), \
    PNFO(ENET0_RGMII_RXC, 1, MLB_0), \
    PNFO(ENET0_RGMII_RXC, 2, NAND), \
    PNFO(ENET0_RGMII_RXC, 3, SDHC_1), \
    PNFO(ENET0_RGMII_RX_CTL, 1, SDHC_1), \
    PNFO(ENET0_RGMII_RXD0, 1, SDHC_1), \
    PNFO(ENET0_RGMII_RXD1, 1, SDHC_1), \
    PNFO(ENET0_RGMII_RXD2, 2, SDHC_1), \
    PNFO(ENET0_RGMII_RXD3, 1, NAND), \
    PNFO(ENET0_RGMII_RXD3, 2, SDHC_1), \
    PNFO(ENET0_MDIO, 1, I2C_3), \
    PNFO(ENET0_MDC, 1, I2C_3), \
    PNFO(ESAI0_FST, 1, MLB_0), \
    PNFO(ESAI0_SCKT, 1, MLB_0), \
    PNFO(ESAI0_TX0, 1, MLB_0), \
    PNFO(SPDIF0_RX, 1, MQS_0), \
    PNFO(SPDIF0_TX, 1, MQS_0), \
    PNFO(SPI3_CS1, 1, I2C_3), \
    PNFO(SPI3_CS1, 3, SPI_2), \
    PNFO(SPI3_CS1, 4, LCD_0), \
    PNFO(MCLK_IN1, 1, I2C_3), \
    PNFO(MCLK_IN1, 3, SPI_2), \
    PNFO(MCLK_IN1, 4, LCD_0), \
    PNFO(MCLK_IN0, 0, AUDIO_CLK_0), \
    PNFO(MCLK_IN0, 3, SPI_2), \
    PNFO(MCLK_OUT0, 0, MCLK_OUT_0), \
    PNFO(MCLK_OUT0, 3, SPI_2), \
    PNFO(UART1_RTS_B, 2, LCD_0), \
    PNFO(UART1_CTS_B, 2, LCD_0), \
    PNFO(SAI0_TXD, 0, SAI_0), \
    PNFO(SAI0_TXD, 1, SAI_1), \
    PNFO(SAI0_TXD, 2, SPI_1), \
    PNFO(SAI0_TXC, 0, SAI_0), \
    PNFO(SAI0_TXC, 1, SAI_1), \
    PNFO(SAI0_TXC, 2, SPI_1), \
    PNFO(SAI0_RXD, 0, SAI_0), \
    PNFO(SAI0_RXD, 1, SAI_1), \
    PNFO(SAI0_RXD, 2, SPI_1), \
    PNFO(SAI0_TXFS, 0, SAI_0), \
    PNFO(SAI0_TXFS, 2, SPI_1), \
    PNFO(SAI1_RXD, 0, SAI_1), \
    PNFO(SAI1_RXD, 1, SAI_0), \
    PNFO(SAI1_RXC, 0, SAI_1), \
    PNFO(SAI1_RXC, 1, SAI_1), \
    PNFO(SAI1_RXFS, 0, SAI_1), \
    PNFO(SAI1_RXFS, 1, SAI_1), \
    PNFO(SPI2_CS0, 0, SPI_2), \
    PNFO(SPI2_SDO, 0, SPI_2), \
    PNFO(SPI2_SDI, 0, SPI_2), \
    PNFO(SPI2_SCK, 0, SPI_2), \
    PNFO(SPI0_SCK, 1, SAI_0), \
    PNFO(SPI0_SCK, 2, M4_0_I2C), \
    PNFO(SPI0_SCK, 3, M4_0_RGPIO), \
    PNFO(SPI0_SDI, 1, SAI_0), \
    PNFO(SPI0_SDI, 2, M4_0_TPM), \
    PNFO(SPI0_SDI, 3, M4_0_RGPIO), \
    PNFO(SPI0_SDO, 1, SAI_0), \
    PNFO(SPI0_SDO, 2, M4_0_I2C), \
    PNFO(SPI0_SDO, 3, M4_0_RGPIO), \
    PNFO(SPI0_CS1, 1, SAI_0), \
    PNFO(SPI0_CS1, 2, SAI_1), \
    PNFO(SPI0_CS0, 1, SAI_0), \
    PNFO(SPI0_CS0, 2, M4_0_TPM), \
    PNFO(SPI0_CS0, 3, M4_0_RGPIO), \
    PNFO(ADC_IN1, 1, M4_0_I2C), \
    PNFO(ADC_IN1, 2, M4_0_RGPIO), \
    PNFO(ADC_IN0, 1, M4_0_I2C), \
    PNFO(ADC_IN0, 2, M4_0_RGPIO), \
    PNFO(ADC_IN3, 1, M4_0_UART), \
    PNFO(ADC_IN3, 2, M4_0_RGPIO), \
    PNFO(ADC_IN3, 3, MCLK_OUT_0), \
    PNFO(ADC_IN2, 1, M4_0_UART), \
    PNFO(ADC_IN2, 2, M4_0_RGPIO), \
    PNFO(ADC_IN2, 3, AUDIO_CLK_0), \
    PNFO(ADC_IN5, 1, M4_0_TPM), \
    PNFO(ADC_IN4, 1, M4_0_TPM), \
    PNFO(FLEXCAN0_RX, 0, CAN_0), \
    PNFO(FLEXCAN0_RX, 1, SAI_2), \
    PNFO(FLEXCAN0_RX, 3, SAI_1), \
    PNFO(FLEXCAN0_TX, 0, CAN_0), \
    PNFO(FLEXCAN0_TX, 1, SAI_2), \
    PNFO(FLEXCAN0_TX, 3, SAI_1), \
    PNFO(FLEXCAN1_RX, 0, CAN_1), \
    PNFO(FLEXCAN1_RX, 1, SAI_2), \
    PNFO(FLEXCAN1_RX, 3, SAI_1), \
    PNFO(FLEXCAN1_TX, 0, CAN_1), \
    PNFO(FLEXCAN1_TX, 1, SAI_3), \
    PNFO(FLEXCAN1_TX, 3, SAI_1), \
    PNFO(FLEXCAN2_RX, 1, SAI_3), \
    PNFO(FLEXCAN2_RX, 2, UART_3), \
    PNFO(FLEXCAN2_RX, 3, SAI_1), \
    PNFO(FLEXCAN2_TX, 1, SAI_3), \
    PNFO(FLEXCAN2_TX, 2, UART_3), \
    PNFO(FLEXCAN2_TX, 3, SAI_1), \
    PNFO(UART0_RX, 1, MQS_0), \
    PNFO(UART0_RX, 2, CAN_0), \
    PNFO(UART0_RX, 3, SC_UART), \
    PNFO(UART0_TX, 1, MQS_0), \
    PNFO(UART0_TX, 2, CAN_0), \
    PNFO(UART0_TX, 3, SC_UART), \
    PNFO(UART2_TX, 2, CAN_1), \
    PNFO(UART2_RX, 2, CAN_1), \
    PNFO(MIPI_DSI0_GPIO0_00, 1, I2C_1), \
    PNFO(MIPI_DSI0_GPIO0_01, 1, I2C_1), \
    PNFO(JTAG_TRST_B, 1, SC_PID0), \
    PNFO(PMIC_I2C_SCL, 0, SC_I2C), \
    PNFO(PMIC_I2C_SDA, 0, SC_I2C), \
    PNFO(SCU_GPIO0_00, 1, SC_UART), \
    PNFO(SCU_GPIO0_00, 2, M4_0_UART), \
    PNFO(SCU_GPIO0_00, 3, UART_3), \
    PNFO(SCU_GPIO0_01, 1, SC_UART), \
    PNFO(SCU_GPIO0_01, 2, M4_0_UART), \
    PNFO(SCU_GPIO0_01, 3, UART_3), \
    PNFO(SCU_GPIO0_01, 4, SC_PID0), \
    PNFO(SCU_BOOT_MODE2, 1, SC_I2C), \
    PNFO(SCU_BOOT_MODE3, 1, SC_I2C), \
    PNFO(CSI_D00, 1, SAI_0), \
    PNFO(CSI_D01, 1, SAI_0), \
    PNFO(CSI_D02, 1, SAI_0), \
    PNFO(CSI_D03, 1, SAI_2), \
    PNFO(CSI_D04, 1, SAI_2), \
    PNFO(CSI_D05, 1, SAI_2), \
    PNFO(CSI_D06, 1, SAI_3), \
    PNFO(CSI_D07, 1, SAI_3), \
    PNFO(CSI_HSYNC, 2, SAI_3), \
    PNFO(CSI_PCLK, 1, CSI_0_I2C_0), \
    PNFO(CSI_PCLK, 2, SPI_1), \
    PNFO(CSI_MCLK, 1, CSI_0_I2C_0), \
    PNFO(CSI_MCLK, 2, SPI_1), \
    PNFO(CSI_EN, 2, I2C_3), \
    PNFO(CSI_EN, 3, SPI_1), \
    PNFO(CSI_RESET, 2, I2C_3), \
    PNFO(CSI_RESET, 3, SPI_1), \
    PNFO(MIPI_CSI0_I2C0_SCL, 0, CSI_0_I2C_0), \
    PNFO(MIPI_CSI0_I2C0_SDA, 0, CSI_0_I2C_0), \
    {0, 0, 0}

#define SC_NUM_PAD_PRIORITY 180

#endif /* SC_PAD_PRIORITY_H */

