
OBJS += $(OUT)/ss/db/v3/ss.o

CONFIGH += $(SRC)/ss/db/v3/config.h $(SRC)/ss/db/v3/rsrc.h

RSRC_MD += $(SRC)/ss/db/v3/resource.txt

CLK_MD += $(SRC)/ss/db/v3/clock.txt

CTRL_MD += $(SRC)/ss/db/v3/control.txt

DIRS += $(OUT)/ss/db/v3

