/*
** ###################################################################
**     Processors:          MX8
**
**     Compilers:           GNU C Compiler
**
**     Abstract:
**         CMSIS Peripheral Access Layer for MX8
**
**     Copyright (c) 2019 NXP
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of the copyright holder nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**
** ###################################################################
*/

/*
 * WARNING! DO NOT EDIT THIS FILE DIRECTLY!
 *
 * This file was generated automatically and any changes may be lost.
 */
#ifndef __HW_IGPIO_REGISTERS_H__
#define __HW_IGPIO_REGISTERS_H__

/* ----------------------------------------------------------------------------
   -- IGPIO Peripheral Access Layer
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup IGPIO_Peripheral_Access_Layer FIGPIO Peripheral Access Layer
 * @{
 */

/** IGPIO - Register Layout Typedef */
typedef struct {
  __IO uint32_t DR;                                /**< IGPIO data register, offset: 0x0 */
  __IO uint32_t GDIR;                              /**< IGPIO direction register, offset: 0x4 */
  __I  uint32_t PSR;                               /**< IGPIO pad status register, offset: 0x8 */
  __IO uint32_t ICR1;                              /**< IGPIO interrupt configuration register1, offset: 0xC */
  __IO uint32_t ICR2;                              /**< IGPIO interrupt configuration register2, offset: 0x10 */
  __IO uint32_t IMR;                               /**< IGPIO interrupt mask register, offset: 0x14 */
  __IO uint32_t ISR;                               /**< IGPIO interrupt status register, offset: 0x18 */
  __IO uint32_t EDGE_SEL;                          /**< IGPIO edge select register, offset: 0x1C */
} IGPIO_Type;

/* ----------------------------------------------------------------------------
   -- IGPIO Register Masks
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup IGPIO_Register_Masks IGPIO Register Masks
 * @{
 */

/*! @name DR - IGPIO data register */
/*! @{ */
#define IGPIO_DR_DR_MASK                          (0xFFFFFFFFU)
#define IGPIO_DR_DR_SHIFT                         (0U)
#define IGPIO_DR_DR(x)                            (((uint32_t)(((uint32_t)(x)) << IGPIO_DR_DR_SHIFT)) & IGPIO_DR_DR_MASK)
/*! @} */

/*! @name GDIR - IGPIO direction register */
/*! @{ */
#define IGPIO_GDIR_GDIR_MASK                      (0xFFFFFFFFU)
#define IGPIO_GDIR_GDIR_SHIFT                     (0U)
/*! GDIR
 *  0b00000000000000000000000000000000..IGPIO is configured as input.
 *  0b00000000000000000000000000000001..IGPIO is configured as output.
 */
#define IGPIO_GDIR_GDIR(x)                        (((uint32_t)(((uint32_t)(x)) << IGPIO_GDIR_GDIR_SHIFT)) & IGPIO_GDIR_GDIR_MASK)
/*! @} */

/*! @name PSR - IGPIO pad status register */
/*! @{ */
#define IGPIO_PSR_PSR_MASK                        (0xFFFFFFFFU)
#define IGPIO_PSR_PSR_SHIFT                       (0U)
#define IGPIO_PSR_PSR(x)                          (((uint32_t)(((uint32_t)(x)) << IGPIO_PSR_PSR_SHIFT)) & IGPIO_PSR_PSR_MASK)
/*! @} */

/*! @name ICR1 - IGPIO interrupt configuration register1 */
/*! @{ */
#define IGPIO_ICR1_ICR0_MASK                      (0x3U)
#define IGPIO_ICR1_ICR0_SHIFT                     (0U)
/*! ICR0
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR1_ICR0(x)                        (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR1_ICR0_SHIFT)) & IGPIO_ICR1_ICR0_MASK)
#define IGPIO_ICR1_ICR1_MASK                      (0xCU)
#define IGPIO_ICR1_ICR1_SHIFT                     (2U)
/*! ICR1
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR1_ICR1(x)                        (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR1_ICR1_SHIFT)) & IGPIO_ICR1_ICR1_MASK)
#define IGPIO_ICR1_ICR2_MASK                      (0x30U)
#define IGPIO_ICR1_ICR2_SHIFT                     (4U)
/*! ICR2
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR1_ICR2(x)                        (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR1_ICR2_SHIFT)) & IGPIO_ICR1_ICR2_MASK)
#define IGPIO_ICR1_ICR3_MASK                      (0xC0U)
#define IGPIO_ICR1_ICR3_SHIFT                     (6U)
/*! ICR3
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR1_ICR3(x)                        (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR1_ICR3_SHIFT)) & IGPIO_ICR1_ICR3_MASK)
#define IGPIO_ICR1_ICR4_MASK                      (0x300U)
#define IGPIO_ICR1_ICR4_SHIFT                     (8U)
/*! ICR4
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR1_ICR4(x)                        (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR1_ICR4_SHIFT)) & IGPIO_ICR1_ICR4_MASK)
#define IGPIO_ICR1_ICR5_MASK                      (0xC00U)
#define IGPIO_ICR1_ICR5_SHIFT                     (10U)
/*! ICR5
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR1_ICR5(x)                        (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR1_ICR5_SHIFT)) & IGPIO_ICR1_ICR5_MASK)
#define IGPIO_ICR1_ICR6_MASK                      (0x3000U)
#define IGPIO_ICR1_ICR6_SHIFT                     (12U)
/*! ICR6
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR1_ICR6(x)                        (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR1_ICR6_SHIFT)) & IGPIO_ICR1_ICR6_MASK)
#define IGPIO_ICR1_ICR7_MASK                      (0xC000U)
#define IGPIO_ICR1_ICR7_SHIFT                     (14U)
/*! ICR7
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR1_ICR7(x)                        (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR1_ICR7_SHIFT)) & IGPIO_ICR1_ICR7_MASK)
#define IGPIO_ICR1_ICR8_MASK                      (0x30000U)
#define IGPIO_ICR1_ICR8_SHIFT                     (16U)
/*! ICR8
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR1_ICR8(x)                        (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR1_ICR8_SHIFT)) & IGPIO_ICR1_ICR8_MASK)
#define IGPIO_ICR1_ICR9_MASK                      (0xC0000U)
#define IGPIO_ICR1_ICR9_SHIFT                     (18U)
/*! ICR9
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR1_ICR9(x)                        (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR1_ICR9_SHIFT)) & IGPIO_ICR1_ICR9_MASK)
#define IGPIO_ICR1_ICR10_MASK                     (0x300000U)
#define IGPIO_ICR1_ICR10_SHIFT                    (20U)
/*! ICR10
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR1_ICR10(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR1_ICR10_SHIFT)) & IGPIO_ICR1_ICR10_MASK)
#define IGPIO_ICR1_ICR11_MASK                     (0xC00000U)
#define IGPIO_ICR1_ICR11_SHIFT                    (22U)
/*! ICR11
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR1_ICR11(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR1_ICR11_SHIFT)) & IGPIO_ICR1_ICR11_MASK)
#define IGPIO_ICR1_ICR12_MASK                     (0x3000000U)
#define IGPIO_ICR1_ICR12_SHIFT                    (24U)
/*! ICR12
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR1_ICR12(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR1_ICR12_SHIFT)) & IGPIO_ICR1_ICR12_MASK)
#define IGPIO_ICR1_ICR13_MASK                     (0xC000000U)
#define IGPIO_ICR1_ICR13_SHIFT                    (26U)
/*! ICR13
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR1_ICR13(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR1_ICR13_SHIFT)) & IGPIO_ICR1_ICR13_MASK)
#define IGPIO_ICR1_ICR14_MASK                     (0x30000000U)
#define IGPIO_ICR1_ICR14_SHIFT                    (28U)
/*! ICR14
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR1_ICR14(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR1_ICR14_SHIFT)) & IGPIO_ICR1_ICR14_MASK)
#define IGPIO_ICR1_ICR15_MASK                     (0xC0000000U)
#define IGPIO_ICR1_ICR15_SHIFT                    (30U)
/*! ICR15
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR1_ICR15(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR1_ICR15_SHIFT)) & IGPIO_ICR1_ICR15_MASK)
/*! @} */

/*! @name ICR2 - IGPIO interrupt configuration register2 */
/*! @{ */
#define IGPIO_ICR2_ICR16_MASK                     (0x3U)
#define IGPIO_ICR2_ICR16_SHIFT                    (0U)
/*! ICR16
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR2_ICR16(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR2_ICR16_SHIFT)) & IGPIO_ICR2_ICR16_MASK)
#define IGPIO_ICR2_ICR17_MASK                     (0xCU)
#define IGPIO_ICR2_ICR17_SHIFT                    (2U)
/*! ICR17
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR2_ICR17(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR2_ICR17_SHIFT)) & IGPIO_ICR2_ICR17_MASK)
#define IGPIO_ICR2_ICR18_MASK                     (0x30U)
#define IGPIO_ICR2_ICR18_SHIFT                    (4U)
/*! ICR18
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR2_ICR18(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR2_ICR18_SHIFT)) & IGPIO_ICR2_ICR18_MASK)
#define IGPIO_ICR2_ICR19_MASK                     (0xC0U)
#define IGPIO_ICR2_ICR19_SHIFT                    (6U)
/*! ICR19
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR2_ICR19(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR2_ICR19_SHIFT)) & IGPIO_ICR2_ICR19_MASK)
#define IGPIO_ICR2_ICR20_MASK                     (0x300U)
#define IGPIO_ICR2_ICR20_SHIFT                    (8U)
/*! ICR20
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR2_ICR20(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR2_ICR20_SHIFT)) & IGPIO_ICR2_ICR20_MASK)
#define IGPIO_ICR2_ICR21_MASK                     (0xC00U)
#define IGPIO_ICR2_ICR21_SHIFT                    (10U)
/*! ICR21
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR2_ICR21(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR2_ICR21_SHIFT)) & IGPIO_ICR2_ICR21_MASK)
#define IGPIO_ICR2_ICR22_MASK                     (0x3000U)
#define IGPIO_ICR2_ICR22_SHIFT                    (12U)
/*! ICR22
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR2_ICR22(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR2_ICR22_SHIFT)) & IGPIO_ICR2_ICR22_MASK)
#define IGPIO_ICR2_ICR23_MASK                     (0xC000U)
#define IGPIO_ICR2_ICR23_SHIFT                    (14U)
/*! ICR23
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR2_ICR23(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR2_ICR23_SHIFT)) & IGPIO_ICR2_ICR23_MASK)
#define IGPIO_ICR2_ICR24_MASK                     (0x30000U)
#define IGPIO_ICR2_ICR24_SHIFT                    (16U)
/*! ICR24
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR2_ICR24(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR2_ICR24_SHIFT)) & IGPIO_ICR2_ICR24_MASK)
#define IGPIO_ICR2_ICR25_MASK                     (0xC0000U)
#define IGPIO_ICR2_ICR25_SHIFT                    (18U)
/*! ICR25
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR2_ICR25(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR2_ICR25_SHIFT)) & IGPIO_ICR2_ICR25_MASK)
#define IGPIO_ICR2_ICR26_MASK                     (0x300000U)
#define IGPIO_ICR2_ICR26_SHIFT                    (20U)
/*! ICR26
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR2_ICR26(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR2_ICR26_SHIFT)) & IGPIO_ICR2_ICR26_MASK)
#define IGPIO_ICR2_ICR27_MASK                     (0xC00000U)
#define IGPIO_ICR2_ICR27_SHIFT                    (22U)
/*! ICR27
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR2_ICR27(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR2_ICR27_SHIFT)) & IGPIO_ICR2_ICR27_MASK)
#define IGPIO_ICR2_ICR28_MASK                     (0x3000000U)
#define IGPIO_ICR2_ICR28_SHIFT                    (24U)
/*! ICR28
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR2_ICR28(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR2_ICR28_SHIFT)) & IGPIO_ICR2_ICR28_MASK)
#define IGPIO_ICR2_ICR29_MASK                     (0xC000000U)
#define IGPIO_ICR2_ICR29_SHIFT                    (26U)
/*! ICR29
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR2_ICR29(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR2_ICR29_SHIFT)) & IGPIO_ICR2_ICR29_MASK)
#define IGPIO_ICR2_ICR30_MASK                     (0x30000000U)
#define IGPIO_ICR2_ICR30_SHIFT                    (28U)
/*! ICR30
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR2_ICR30(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR2_ICR30_SHIFT)) & IGPIO_ICR2_ICR30_MASK)
#define IGPIO_ICR2_ICR31_MASK                     (0xC0000000U)
#define IGPIO_ICR2_ICR31_SHIFT                    (30U)
/*! ICR31
 *  0b00..Interrupt n is low-level sensitive.
 *  0b01..Interrupt n is high-level sensitive.
 *  0b10..Interrupt n is rising-edge sensitive.
 *  0b11..Interrupt n is falling-edge sensitive.
 */
#define IGPIO_ICR2_ICR31(x)                       (((uint32_t)(((uint32_t)(x)) << IGPIO_ICR2_ICR31_SHIFT)) & IGPIO_ICR2_ICR31_MASK)
/*! @} */

/*! @name IMR - IGPIO interrupt mask register */
/*! @{ */
#define IGPIO_IMR_IMR_MASK                        (0xFFFFFFFFU)
#define IGPIO_IMR_IMR_SHIFT                       (0U)
/*! IMR
 *  0b00000000000000000000000000000000..Interrupt n is disabled.
 *  0b00000000000000000000000000000001..Interrupt n is enabled.
 */
#define IGPIO_IMR_IMR(x)                          (((uint32_t)(((uint32_t)(x)) << IGPIO_IMR_IMR_SHIFT)) & IGPIO_IMR_IMR_MASK)
/*! @} */

/*! @name ISR - IGPIO interrupt status register */
/*! @{ */
#define IGPIO_ISR_ISR_MASK                        (0xFFFFFFFFU)
#define IGPIO_ISR_ISR_SHIFT                       (0U)
#define IGPIO_ISR_ISR(x)                          (((uint32_t)(((uint32_t)(x)) << IGPIO_ISR_ISR_SHIFT)) & IGPIO_ISR_ISR_MASK)
/*! @} */

/*! @name EDGE_SEL - IGPIO edge select register */
/*! @{ */
#define IGPIO_EDGE_SEL_IGPIO_EDGE_SEL_MASK         (0xFFFFFFFFU)
#define IGPIO_EDGE_SEL_IGPIO_EDGE_SEL_SHIFT        (0U)
#define IGPIO_EDGE_SEL_IGPIO_EDGE_SEL(x)           (((uint32_t)(((uint32_t)(x)) << IGPIO_EDGE_SEL_IGPIO_EDGE_SEL_SHIFT)) & IGPIO_EDGE_SEL_IGPIO_EDGE_SEL_MASK)
/*! @} */

/*!
 * @}
 */ /* end of group IGPIO_Register_Masks */

/* IGPIO - Peripheral instance base addresses */
/** Peripheral GPIO1 base pointer */
#define GPIO0                                    ((IGPIO_Type *)GPIO0_BASE)
/** Peripheral GPIO1 base pointer */
#define GPIO1                                    ((IGPIO_Type *)GPIO1_BASE)
/** Peripheral GPIO2 base pointer */
#define GPIO2                                    ((IGPIO_Type *)GPIO2_BASE)
/** Peripheral GPIO3 base pointer */
#define GPIO3                                    ((IGPIO_Type *)GPIO3_BASE)
/** Peripheral GPIO4 base pointer */
#define GPIO4                                    ((IGPIO_Type *)GPIO4_BASE)
/** Peripheral GPIO5 base pointer */
#define GPIO5                                    ((IGPIO_Type *)GPIO5_BASE)
/** Peripheral GPIO5 base pointer */
#define GPIO6                                    ((IGPIO_Type *)GPIO6_BASE)
/** Peripheral GPIO5 base pointer */
#define GPIO7                                    ((IGPIO_Type *)GPIO7_BASE)
/** Array initializer of IGPIO peripheral base addresses */
#define IGPIO_BASE_ADDRS                          { GPIO0_BASE, GPIO1_BASE, \
                                                    GPIO2_BASE, GPIO3_BASE, \
                                                    GPIO4_BASE, GPIO5_BASE, \
                                                    GPIO6_BASE, GPIO7_BASE }
/** Array initializer of IGPIO peripheral base pointers */
#define IGPIO_BASE_PTRS                           { GPIO0, GPIO1, GPIO2, \
                                                    GPIO3, GPIO4, GPIO5, \
                                                    GPIO6, GPIO7 }
/** Interrupt vectors for the IGPIO peripheral type */
#define IGPIO_IRQS                                { NotAvail_IRQn }
#define IGPIO_COMBINED_LOW_IRQS                   { NotAvail_IRQn }
#define IGPIO_COMBINED_HIGH_IRQS                  { NotAvail_IRQn }

/*!
 * @}
 */ /* end of group IGPIO_Peripheral_Access_Layer */

#endif /* __HW_IGPIO_REGISTERS_H__ */
